manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mykeyboard
      url-base: https://github.com/bvbhu
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-qmk-rgb-matrix
      remote: mykeyboard
      revision: main
      path: modules/rgb-matrix
  self:
    path: config
